<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAaeI9Rg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAaeI9Rg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAaeI9Rg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAaeI9Rg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAaeI9Rg\App_KernelDevDebugContainer([
    'container.build_hash' => 'AaeI9Rg',
    'container.build_id' => 'c0bfc5b1',
    'container.build_time' => 1717760203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAaeI9Rg');
